// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN1Bgy-xkAYqqzsSAlya4dQZ1htAYAdGM',
    appId: '1:364277189955:web:6a756ad6a2b04c0da7b3f6',
    messagingSenderId: '364277189955',
    projectId: 'todoapp-bee60',
    authDomain: 'todoapp-bee60.firebaseapp.com',
    storageBucket: 'todoapp-bee60.firebasestorage.app',
    measurementId: 'G-8XDJWF8GZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjDokDGmW0g0dcaab4qa0frAjC2uDNREg',
    appId: '1:364277189955:android:56136bfa7242fd9da7b3f6',
    messagingSenderId: '364277189955',
    projectId: 'todoapp-bee60',
    storageBucket: 'todoapp-bee60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuZY7a5wn5BFhfLx8ITajTq3irau3ATjY',
    appId: '1:364277189955:ios:feeb84240e17dc00a7b3f6',
    messagingSenderId: '364277189955',
    projectId: 'todoapp-bee60',
    storageBucket: 'todoapp-bee60.firebasestorage.app',
    iosBundleId: 'com.example.contactBookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuZY7a5wn5BFhfLx8ITajTq3irau3ATjY',
    appId: '1:364277189955:ios:feeb84240e17dc00a7b3f6',
    messagingSenderId: '364277189955',
    projectId: 'todoapp-bee60',
    storageBucket: 'todoapp-bee60.firebasestorage.app',
    iosBundleId: 'com.example.contactBookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN1Bgy-xkAYqqzsSAlya4dQZ1htAYAdGM',
    appId: '1:364277189955:web:b22310f833592f4fa7b3f6',
    messagingSenderId: '364277189955',
    projectId: 'todoapp-bee60',
    authDomain: 'todoapp-bee60.firebaseapp.com',
    storageBucket: 'todoapp-bee60.firebasestorage.app',
    measurementId: 'G-H888GXJ50L',
  );
}
